// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4zMVR2WNszbgNQ2czzjmlA4RES2PCFnU',
    appId: '1:293467875040:web:aec65cebd73949458e5285',
    messagingSenderId: '293467875040',
    projectId: 'twitter-app-2e268',
    authDomain: 'twitter-app-2e268.firebaseapp.com',
    storageBucket: 'twitter-app-2e268.appspot.com',
    measurementId: 'G-7DRN40DQTB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDfPm89hR4X3eRh17Sq0dnWNSIoy3zuOw',
    appId: '1:293467875040:android:8f48cce34280d4868e5285',
    messagingSenderId: '293467875040',
    projectId: 'twitter-app-2e268',
    storageBucket: 'twitter-app-2e268.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYxpr6A4pmK4R2NClfjvu_l7dbquhMUlk',
    appId: '1:293467875040:ios:0b2af808c521a1a68e5285',
    messagingSenderId: '293467875040',
    projectId: 'twitter-app-2e268',
    storageBucket: 'twitter-app-2e268.appspot.com',
    iosClientId: '293467875040-i6qod9kv1ls2ctbfqnc4urervced0d3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYxpr6A4pmK4R2NClfjvu_l7dbquhMUlk',
    appId: '1:293467875040:ios:0b2af808c521a1a68e5285',
    messagingSenderId: '293467875040',
    projectId: 'twitter-app-2e268',
    storageBucket: 'twitter-app-2e268.appspot.com',
    iosClientId: '293467875040-i6qod9kv1ls2ctbfqnc4urervced0d3i.apps.googleusercontent.com',
    iosBundleId: 'com.example.twitterClone',
  );
}
